services:
  mongodb:
    container_name: catalog-mongodb
    image: mongo:6
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    container_name: catalog-api
    image: node:18
    working_dir: /usr/src/app
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/catalog
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./dist:/usr/src/app/dist/
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
    links:
      - mongodb
    depends_on:
      - mongodb
